# Generated by Django 5.1 on 2024-08-31 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladmcol_environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaFuenteEspacial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Croquis_Campo', 'Croquis_Campo'), ('Datos_Crudos', 'Datos_Crudos'), ('Ortofoto', 'Ortofoto'), ('Informe_Tecnico', 'Informe_Tecnico'), ('Registro_Fotografico', 'Registro_Fotografico')], max_length=50)),
                ('descripcion', models.CharField()),
                ('metadato', models.CharField()),
                ('estado_disponibilidad', models.CharField(choices=[('Convertido', 'Convertido'), ('Desconocido', 'Desconocido'), ('Disponible', 'Disponible')])),
                ('tipo_principal', models.CharField(choices=[('imagen', 'imagen'), ('Documento', 'Documento'), ('Mapa', 'Mapa')])),
                ('fecha_documento_fuente', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtArchivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aceptacion', models.DateField()),
                ('datos', models.CharField()),
                ('extraccion', models.DateField()),
                ('fecha_grabacion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('espacio_nombres', models.CharField()),
                ('local', models.CharField()),
                ('fuente_espacial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MaFuenteEspacial', to='ladmcol_environment.mafuenteespacial', unique=True)),
            ],
        ),
    ]
