# Generated by Django 5.1 on 2024-08-31 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladmcol_environment', '0002_mafuenteespacial_extarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extarchivo',
            name='fuente_espacial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExtArchivo', to='ladmcol_environment.mafuenteespacial', unique=True),
        ),
        migrations.CreateModel(
            name='ColDrr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField()),
                ('ma_uab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ColDrr', to='ladmcol_environment.mauab')),
            ],
        ),
    ]
