# Generated by Django 5.1 on 2024-09-01 01:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladmcol_environment', '0003_alter_extarchivo_fuente_espacial_id_coldrr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColFuenteAdministrativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_disponibilidad', models.CharField(choices=[('Convertido', 'Convertido'), ('Desconocido', 'Desconocido'), ('Disponible', 'Disponible')])),
                ('observacion', models.CharField()),
            ],
            options={
                'db_table': "ma_col'.'ColFuenteAdministrativa",
            },
        ),
        migrations.CreateModel(
            name='ColUnidadEspacial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tipo_unidad_espacial', models.CharField(choices=[('MA_UAB_ReservaForetsalProtectoraProductora', 'RFPP'), ('MA_UAB_ReservaLey2da', 'Reserva ley 2da'), ('MA_UAB_ReservaForestalProtectoraNacional', 'RFPN'), ('MA_UAB_SustraccionLey2da', 'Sustraccion ley 2da')])),
            ],
            options={
                'db_table': "ma_col'.'ColUnidadEspacial",
            },
        ),
        migrations.CreateModel(
            name='ExtInteresado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
            ],
            options={
                'db_table': "ma_col'.'ExtInteresado",
            },
        ),
        migrations.AlterModelTable(
            name='coldrr',
            table='ma_col',
        ),
        migrations.AlterModelTable(
            name='extarchivo',
            table="ma_col'.'ExtArchivo",
        ),
        migrations.AlterModelTable(
            name='mafuenteespacial',
            table="ma_col'.'MaFuenteEspacial",
        ),
        migrations.AlterModelTable(
            name='mauab',
            table="ma_col'.'MaUab",
        ),
        migrations.CreateModel(
            name='ColRrrFuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('col_drr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ColRrrFuente', to='ladmcol_environment.coldrr')),
                ('col_fuente_administrativa_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ColRrrFuente', to='ladmcol_environment.colfuenteadministrativa')),
            ],
            options={
                'db_table': "ma_col'.'ColRrrFuente",
            },
        ),
        migrations.CreateModel(
            name='ColAgrupacionUnidadesEspaciales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_jerarquico', models.IntegerField()),
                ('nombre', models.CharField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('col_unidad_espacial_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ColAgrupacionUnidadesEspaciales', to='ladmcol_environment.colunidadespacial')),
            ],
            options={
                'db_table': "ma_col'.'ColAgrupacionUnidadesEspaciales",
            },
        ),
        migrations.CreateModel(
            name='ExtDireccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Domicilio_Particular', 'Domicilio_Particular'), ('Domicilio_Comercial', 'Domicilio_Comercial')])),
                ('calle', models.CharField()),
                ('codigo_postal', models.CharField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('sector', models.CharField()),
                ('ext_interesado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExtDireccion', to='ladmcol_environment.extinteresado')),
            ],
            options={
                'db_table': "ma_col'.'ExtDireccion",
            },
        ),
        migrations.CreateModel(
            name='MaInteresado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Grupo_Civil', 'Grupo_Civil'), ('Grupo_Empresarial', 'Grupo_Empresarial'), ('Grupo_Etnico', 'Grupo_Etnico'), ('Grupo_Mixto', 'Grupo_Mixto')])),
                ('nombre', models.CharField()),
                ('col_drr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MaInteresado', to='ladmcol_environment.coldrr')),
            ],
            options={
                'db_table': "ma_col'.'MaInteresado",
            },
        ),
        migrations.AddField(
            model_name='extinteresado',
            name='ma_interesado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExtInteresado', to='ladmcol_environment.mainteresado'),
        ),
    ]
