# Generated by Django 5.1 on 2024-08-30 16:13

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_mpio', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
