# Generated by Django 5.1 on 2024-08-30 18:34

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_municipality_propertylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('number_id', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('land_use', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('agricultural', 'agricultural')], max_length=100)),
                ('date_create', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='app1.municipality')),
                ('party_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='app1.party')),
            ],
        ),
    ]
